spring:
  # Configuration de la base de données
  datasource:
    url: jdbc:mysql://localhost:3306/excel_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # Configuration de RabbitMQ (CORRIGÉE)
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

  # Configuration de JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Configuration du téléversement de fichiers
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# Configuration du serveur
server:
  port: 8080

# Configuration du microservice Python
python:
  processor:
    url: http://localhost:8000

# Clé secrète JWT
jwt:
  secret: VotreCleSecreteTresLongueEtDifficileADevinerPourLaProduction

# Configuration du service de gestion des utilisateurs
user:
  management:
    service:
      url: http://localhost:8081