spring:
  datasource:
    url: jdbc:mysql://localhost:3306/excel_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # ou validate / create / none selon l'environnement
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8080

python:
  processor:
    # URL du microservice Python qui traite les fichiers Excel
    url: http://localhost:8000
